GET{{protocol}}{{host}}:{{port}}/auctions
Accept: application/json

> {%
 client.test(
     "Request executed successfully",
     function(){
         client.assert(response.status == 200, "Response status is not 200");
     }
 )
 %}

###

GET {{protocol}}{{host}}:{{port}}/auctions/1

###

POST {{protocol}}{{host}}:{{port}}/auctions/new
Content-Type: application/json

{
  "name": "Kaas",
  "price": 5,
  "bids":5,
  "duration":55
}

> {%
    client.test(
        "Request executed successfully",
        function(){

        }
    )
%}
###

### Update a auction with id 1 (Should be 200)
PATCH {{protocol}}{{host}}:{{port}}/auctions/update/1
Content-Type: application/json

{
"name": "Test1",
"price":"6",
"bids":"1",
"duration":"1"
}

###

###Update a auction with id 'y' (Should be 404)
PATCH {{protocol}}{{host}}:{{port}}/auctions/update/y
Content-Type: application/json

{
  "name": "Test1",
  "price":"6",
  "bids":"1",
  "duration":"1"
}

###
DELETE {{protocol}}{{host}}:{{port}}/auctions/delete/1

###

DELETE {{protocol}}{{host}}:{{port}}/auctions/delete/5
Accept: application/json

> {%
    client.test(
        "Bad Delete Test",
        function(){
            client.assert(response.status == 404, "Response status is not 404");
        }
    )
%}
