GET{{protocol}}{{host}}:{{port}}/auctions
Accept: application/json

> {%
 client.test(
     "Request executed successfully",
     function(){
         client.assert(response.status == 200, "Response status is not 200");
     }
 )
 %}

###

GET {{protocol}}{{host}}:{{port}}/auctions/1

###

POST {{protocol}}{{host}}:{{port}}/auctions/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRLRk5tOVVxa2UyZXlwb2JuVlNrZW4uM3RuTENLNFFBMUYwYTFiUWx2MFhYdUVoblVGT2lDNiIsImlhdCI6MTY5ODE0NzU0NCwiZXhwIjoxNjk4MTUxMTQ0fQ.MOZ767JyCcRZxobFw8B7boilkiSFjLyqySyOAjXyoe8

{
  "name": "Kaas",
  "price": 5,
  "bids":5,
  "duration":55
}


> {%
    client.test(
        "Request executed successfully",
        function(){

        }
    )
%}

###

### Update a auction with id 1 (Should be 200)

PATCH {{protocol}}{{host}}:{{port}}/auctions/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRWSk9yZC9pRG1oVGguTXpwNlVqc2JlRHAvcUlQL1BaQy5QT1hVak04Q3QzR2dTc1BvNGJHMiIsImlhdCI6MTY5ODE3OTg1MCwiZXhwIjoxNjk4MTgzNDUwfQ.lq5ie2K_mL2pqomKs7LQz8pzaDe7XcjWXqAIyAxs3vE

{
"name": "Test1",
"price":"6",
"bids":"1",
"duration":"1"
}

###

###Update a auction with id 'y' (Should be 404)
PATCH {{protocol}}{{host}}:{{port}}/auctions/update/y
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test1",
  "price":"6",
  "bids":"1",
  "duration":"1"
}
> {%
    client.global.set("token", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6IiQyYiQxMCRLRk5tOVVxa2UyZXlwb2JuVlNrZW4uM3RuTENLNFFBMUYwYTFiUWx2MFhYdUVoblVGT2lDNiIsImlhdCI6MTY5ODE0NzU0NCwiZXhwIjoxNjk4MTUxMTQ0fQ.MOZ767JyCcRZxobFw8B7boilkiSFjLyqySyOAjXyoe8");
%}
###
DELETE {{protocol}}{{host}}:{{port}}/auctions/1
Accept: application/json
Authorization: Bearer {{token}}

> {%
    client.test(
        "Bad Delete Test",
        function(){
            client.assert(response.status == 404, "Response status is not 404");
        }
    )
%}
